name: Xcode - Build and Analyze

on:
  push:
    branches: [ "3.X" ]
  pull_request:
    branches: [ "3.X" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Deps
        run: |
          pod repo update
          pod install
      - name: Build
        run:  xcodebuild -project OnionBrowser.xcodeproj -scheme OnionBrowser -archivePath OnionBrowser.xcarchive archive  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Pack
        run: zip -r artifact.zip Clone-Calculator.xcarchive 
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: artifact.zip
          retention-days: 5
